baseURL = "http://example.org/"
languageCode = "en-gb"
title = "Visual Garden"
disableKinds = ["section"]
pygmentsCodeFences = false
pygmentsUseClasses = false

[minify]
  minifyOutput = true

[permalinks]
  post = ":slug/"

[params]
  description = "A moodboard of graphic inspiration."
  keywords = "mood, moodboard, design inspiration"
  cloudinary_url = "https://res.cloudinary.com/harrycresswell/image/upload/"



[menu]
  [[menu.main]]
    pageRef = "about"
    name = "About"
    url = "/about"
    weight = 5
  [[menu.main]]
    pageRef = "tags"
    name = "Tags"
    url = "/tags"
    weight = 10