[context.production.environment]
  HUGO_VERSION = "0.148.2"
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.148.2"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.148.2"

[build]
  publish = "public"
  command = "hugo --gc --minify -b https://garden.tomasjgonzalez.com"

# Redirect old Netlify URL to custom domain
[[redirects]]
from = "https://main--visual-garden.netlify.app/*"
to = "https://garden.tomasjgonzalez.com/:splat"
status = 301
force = true

# Cloudinary
[[redirects]]
from = "/images/*"
to = "https://res.cloudinary.com/tomasgo/image/upload/:splat"
status = 200

# Netlify Headers
[[headers]]
  for = "/images/*"
  [headers.values]
    # Cache for one year
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"