name: Upload images to Cloudinary

on:
  push:
    paths:
      - 'assets/uploads/**'
      - 'content/post/**'
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Upload images to Cloudinary
        env:
          CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}
        run: |
          shopt -s globstar nullglob extglob
          FILES=(assets/uploads/**/*.* content/post/**/*.@(jpg|jpeg|png|webp|avif|gif))
          if [ ${#FILES[@]} -eq 0 ]; then
            echo "No files to upload."
            exit 0
          fi
          for f in "${FILES[@]}"; do
            # Determine relative path and public_id from source directory
            if [[ "$f" == assets/uploads/* ]]; then
              rel="${f#assets/uploads/}"
              name_no_ext="${rel%.*}"
            else
              rel="${f#content/post/}"
              # Prefix with post/ to keep structure stable in Cloudinary
              name_no_ext="post/${rel%.*}"
            fi
            # Use a stable folder and deterministic public_id; overwrite to keep in sync
            npx --yes @cloudinary/cli cld uploader upload "$f" \
              --folder "visual-garden" \
              --public_id "$name_no_ext" \
              --use_filename=false \
              --unique_filename=false \
              --overwrite=true \
              --invalidate=true
          done

      - name: List uploaded URLs
        if: always()
        env:
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
        run: |
          echo "Uploaded files (by relative path):"
          for f in assets/uploads/**/*.* content/post/**/*.@(jpg|jpeg|png|webp|avif|gif); do
            [ -f "$f" ] || continue
            if [[ "$f" == assets/uploads/* ]]; then
              rel="${f#assets/uploads/}"
              name_no_ext="${rel%.*}"
            else
              rel="${f#content/post/}"
              name_no_ext="post/${rel%.*}"
            fi
            echo "https://res.cloudinary.com/${CLOUDINARY_CLOUD_NAME}/image/upload/visual-garden/${name_no_ext}.jpg"
          done


