name: Upload images to Cloudinary

on:
  push:
    paths:
      - 'assets/uploads/**'
      - 'content/post/**'
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Verify CLI availability
        run: |
          node -v
          npm -v
          python3 -V || true
          pip3 -V || true

      - name: Install Cloudinary CLI (pip)
        run: |
          python3 -m pip install --user --upgrade cloudinary-cli
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          cld --version

      - name: Upload images to Cloudinary
        env:
          CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}
        run: |
          mapfile -t FILES < <(\
            find assets/uploads content/post -type f \( \
              -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.webp' -o -iname '*.avif' -o -iname '*.gif' \
            \) 2>/dev/null || true)
          if [ ${#FILES[@]} -eq 0 ]; then
            echo "No files to upload."
            exit 0
          fi
          for f in "${FILES[@]}"; do
            # Determine relative path and public_id from source directory
            if [[ "$f" == assets/uploads/* ]]; then
              rel="${f#assets/uploads/}"
              name_no_ext="${rel%.*}"
            else
              rel="${f#content/post/}"
              # Prefix with post/ to keep structure stable in Cloudinary
              name_no_ext="post/${rel%.*}"
            fi
            # Slugify the public id for safety (lowercase, dashes, keep slashes)
            slug=$(echo "$name_no_ext" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9\/]+/-/g; s/-+/-/g; s#(^|/)\-+#\1#g; s#\-+($|/)#\1#g')
            # Use a stable folder and deterministic public_id; overwrite to keep in sync
            cld uploader upload "$f" \
              --folder "tomas-master/visual-garden" \
              --public_id "$slug" \
              --use_filename=false \
              --unique_filename=false \
              --overwrite=true \
              --invalidate=true
          done

      - name: List uploaded URLs
        if: always()
        env:
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
        run: |
          echo "Uploaded files (by relative path):"
          mapfile -t FILES < <(\
            find assets/uploads content/post -type f \( \
              -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.webp' -o -iname '*.avif' -o -iname '*.gif' \
            \) 2>/dev/null || true)
          for f in "${FILES[@]}"; do
            if [[ "$f" == assets/uploads/* ]]; then
              rel="${f#assets/uploads/}"
              name_no_ext="${rel%.*}"
            else
              rel="${f#content/post/}"
              name_no_ext="post/${rel%.*}"
            fi
            slug=$(echo "$name_no_ext" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9\/]+/-/g; s/-+/-/g; s#(^|/)\-+#\1#g; s#\-+($|/)#\1#g')
            echo "https://res.cloudinary.com/${CLOUDINARY_CLOUD_NAME}/image/upload/tomas-master/visual-garden/${slug}.jpg"
          done


